#%RAML 1.0
baseUri: http://localhost:8081/api
title: Retail Omnichannel Experience API

traits: 
  geoSearch: !include traits/geoSearch.raml

uses:

  common: types/common-types.raml
  meta: types/metadata-types.raml
  hyper: types/hypermedia-types.raml
  collection: collections.raml
  geography: types/geography-types.raml
  payment: types/payment-types.raml
  contact: types/contact-types.raml
  fulfillment: types/fulfillment-types.raml
  taxonomy: types/taxonomy-types.raml
  customer: customer-types.raml
  channel: channel-types.raml
  order: order-types.raml
  product: types/product-types.raml
  session: session-types.raml
  inventory: types/inventory-types.raml
  store: types/store-types.raml
  partner: types/partner-types.raml

types:
        
  ContactMethodCollectionResponse:
    type: hyper.CollectionResponse
    properties:
      contactMethods: contact.ContactMethod[]
      
  ContactMethodResponse:
    type: contact.ContactMethod

  ChannelCollectionResponse:
    type: hyper.CollectionResponse
    properties:
      channels: channel.Channel[]
      
  ChannelResponse:
    type: channel.Channel

  FulfillmentMethodCollectionResponse:
    type: hyper.CollectionResponse
    properties:
      fulfillmentMethods: fulfillment.Fulfillment[]

  StoreCollectionResponse:
    type: hyper.CollectionResponse
    properties:
      stores: store.StoreInfo[]
 
  StoreResponse:
    type: store.StoreInfo

  PartnerCollectionResponse:
    type: hyper.CollectionResponse
    properties:
      partners: partner.PartnerInfo[]
 
  PartnerResponse:
    type: partner.PartnerInfo
    
  CategoryCollectionResponse:
    type: hyper.CollectionResponse
    properties:
      categories: taxonomy.Category[]
      
  CategoryResponse:
    type: taxonomy.Category

  SalesOrderCollectionResponse:
    type: hyper.CollectionResponse
    properties:
      orders: order.SalesOrder[]
      
  OrderCollectionResponse:
    type: hyper.CollectionResponse
    properties:
      orders: order.Order[]
          
  SalesOrderResponse:
    type: order.SalesOrderHeader
  
  SalesOrderPaymentMethodResponse:
    type: payment.PaymentMethod
    
  SalesOrderFulfillmentResponse:
    type: fulfillment.Fulfillment
        
  SalesOrderItemCollectionResponse:
    type: order.SalesOrderItems

  ProductResponse:
    type: product.Product

  ProductCollectionResponse:
    type: hyper.CollectionResponse
    properties:
      products: product.Product[]
  
  FeatureCollectionResponse:
    type: hyper.CollectionResponse
    properties:
      features: product.ProductFeature[]

  FeatureResponse:
    type: product.ProductFeature
    properties:

  ProductVariantCollectionResponse:
    type: hyper.CollectionResponse
    properties:
      variants: product.ProductVariant[]

  ProductVariantResponse:
    type: product.ProductVariant
        
  ProductVariantAvailabilityResponse:
    type: inventory.Availability
    properties:

  ShoppingCartCollectionResponse:
    type: hyper.CollectionResponse
    properties:
      shoppingCarts: session.ShoppingCart[]
      
  ShoppingCartResponse:
    type: session.ShoppingCart

  InventoryCollectionResponse:
    type: hyper.CollectionResponse
    properties: 
      inventory: inventory.WarehouseInventory[]
      
  InventoryResponse:
    type: inventory.WarehouseInventory
    properties:

/customers:
  type:
    collection.collection:
      collectionResponseType: customer.CustomerCollectionResponse
      collectionMemberPrototypeType: customer.Customer
      collectionMemberResponseType: customer.CustomerResponse
  post:
    body:
      application/json:
        example: |
          {
                "identifier": "deb89058-77fb-4e97-8c83-6506c38cacf8",
                "firstName": "Jason",
                "lastName": "Bourne",
                "paymentMethods": [
                    {
                      "paymentMethodType":{  
                        "medium":"CARD",
                        "issuer":"BANK",
                        "name":"VISA"
                      }
                    }
                ],
                "deliveryAddresses": [
                    {
                      "type": "BILLING",
                      "identifier":"deb89058-77fb-4e97-8c83-6506c3855555",
                      "address":"Main street 122",
                      "city":"San Francisco",
                      "state":"California",
                      "postalCode":"90210",
                      "recipient":"Jason Bourne",
                      "country":"US",
                      "secondaryAddress": null,
                      "mailStopCode": null,
                      "attention": null
                    }
                ]
              }

    responses:
      201:
        body: 
          application/json:    
            example: |
              {
                "identifier": "deb89058-77fb-4e97-8c83-6506c38cacf8",
                "firstName": "Jason",
                "lastName": "Bourne",
                "paymentMethods": [
                    {
                      "identifier":"deb89058-77fb-4e97-8c83-6506c38c4444",
                      "paymentMethodType":{  
                        "medium":"CARD",
                        "issuer":"BANK",
                        "name":"VISA"
                      }
                    }
                ],
                "deliveryAddresses": [
                    {
                      "type": "BILLING",
                      "identifier":"deb89058-77fb-4e97-8c83-6506c3855555",
                      "address":"Main street 122",
                      "city":"San Francisco",
                      "state":"California",
                      "postalCode":"90210",
                      "recipient":"Jason Bourne",
                      "country":"US",
                      "secondaryAddress": null,
                      "mailStopCode": null,
                      "attention": null
                    }
                ]
              }
              
  get:
    is: &queryableCollection [ collection.pageable, collection.sortable ]
    queryParameters:
      firstName: string
      lastName: string
    responses: 
      200:
        body: 
          application/json:
            example: |
              {
                "_links": {
                    "self": {
                      "href": "https://mocksvc.mulesoft.com/mocks/226604b1-d88b-4e3b-8a5c-4c299e70db6c/customers"
                  }
                },
                "_meta": {
                  "messages": [],
                  "totalItems": 1,
                  "offset": 0,
                  "limit": 10                
                },
                "customers": [
                  {
                    "identifier": "deb89058-77fb-4e97-8c83-6506c38cacf8",
                    "firstName": "Jason",
                    "lastName": "Bourne",
                    "paymentMethods": [
                        {
                          "paymentMethodType":{  
                            "medium":"CARD",
                            "issuer":"BANK",
                            "name":"VISA"
                          }
                        }
                    ],
                    "deliveryAddresses": [
                        {
                          "type": "BILLING",
                          "address":"Main street 122",
                          "city":"San Francisco",
                          "state":"California",
                          "postalCode":"90210",
                          "recipient":"Jason Bourne",
                          "country":"US",
                          "secondaryAddress":"",
                          "mailStopCode":"",
                          "attention":""
                        }
                    ]
                  }
                ]
              }
              
  /{customerId}:
    uriParameters:
      customerId:
        type: string
    type:
      collection.collectionMember:
        collectionMemberResponseType: customer.CustomerResponse
        collectionMemberPrototypeType: customer.Customer
    get:
      responses: 
        200:
          body: 
            application/json:
              example: |
                {  
                  "identifier":"deb89058-77fb-4e97-8c83-6506c38cacf8",
                  "firstName":"Jason",
                  "lastName":"Bourne",
                  "paymentMethods":[  
                    {  
                      "paymentMethodType":{  
                        "medium":"CARD",
                        "issuer":"BANK",
                        "name":"VISA"
                      }
                    }
                  ],
                  "deliveryAddresses":[  
                    {  
                      "address":"Main street 122",
                      "type": "BILLING",
                      "city":"San Francisco",
                      "state":"California",
                      "postalCode":"90210",
                      "recipient":"Jason Bourne",
                      "country":"US",
                      "secondaryAddress":null,
                      "mailStopCode":null,
                      "attention":null
                    },
                    {  
                      "address":"Main street 122",
                      "type": "SHIPPING",
                      "city":"San Francisco",
                      "state":"California",
                      "postalCode":"90210",
                      "recipient":"Jason Bourne",
                      "country":"US",
                      "secondaryAddress":null,
                      "mailStopCode":null,
                      "attention":null
                    }
                  ]
                }
    put:
      body: 
            application/json:
              example:  
                  { 
                    "identifier":"deb89058-77fb-4e97-8c83-6506c38cacf8",
                    "firstName":"Jason",
                    "lastName":"Bourne",
                    "paymentMethods":[  
                      {  
                        "paymentMethodType":{  
                          "medium":"CARD",
                          "issuer":"BANK",
                          "name":"VISA"
                        }
                      }
                    ],
                    "deliveryAddresses":[  
                      {
                        "type": "BILLING",
                        "address":"Main street 122",
                        "city":"San Francisco",
                        "state":"California",
                        "postalCode":"90210",
                        "recipient":"Jason Bourne",
                        "country":"US",
                        "secondaryAddress": null,
                        "mailStopCode": null,
                        "attention":null
                      }, 
                      {
                        "type": "SHIPPING",
                        "address":"Main street 122",
                        "city":"San Francisco",
                        "state":"California",
                        "postalCode":"90210",
                        "recipient":"Jason Bourne",
                        "country":"US",
                        "secondaryAddress": null,
                        "mailStopCode": null,
                        "attention": null
                      }
                    ]
                  }
      responses: 
        200:
          body: 
            application/json:
              example: 
                  
                  {  
                    "identifier":"deb89058-77fb-4e97-8c83-6506c38cacf8",
                    "firstName":"Jason",
                    "lastName":"Bourne",
                    "paymentMethods":[  
                      {  
                        "paymentMethodType":{  
                          "medium":"CARD",
                          "issuer":"BANK",
                          "name":"VISA"
                        }
                      }
                    ],
                    "deliveryAddresses":[  
                      {
                        "type": "BILLING",
                        "address":"Main street 122",
                        "city":"San Francisco",
                        "state":"California",
                        "postalCode":"90210",
                        "recipient":"Jason Bourne",
                        "country":"US",
                        "secondaryAddress": null,
                        "mailStopCode": null,
                        "attention": null
                      }, 
                      {
                        "type": "SHIPPING",
                        "address":"Main street 122",
                        "city":"San Francisco",
                        "state":"California",
                        "postalCode":"90210",
                        "recipient":"Jason Bourne",
                        "country":"US",
                        "secondaryAddress": null,
                        "mailStopCode": null,
                        "attention": null
                      }
                    ]
                  }                           
              
              
    /deliveryAddresses:
      type:
        collection.collection:
          collectionResponseType: customer.DeliveryAddressCollectionResponse
          collectionMemberPrototypeType: geography.PostalAddress
          collectionMemberResponseType: customer.DeliveryAddressResponse
      get:
        is: *queryableCollection
        responses: 
          200:
            body: 
              application/json:
                example: | 
                  {
                    "_links": {
                      "self": {
                        "href": "https://mocksvc.mulesoft.com/mocks/226604b1-d88b-4e3b-8a5c-4c299e70db6c/customers/deb89058-77fb-4e97-8c83-6506c38cacf8/deliveryAddresses"
                      }
                    },
                    "_meta": {
                      "messages": [],
                      "totalItems": 1,
                      "offset": 0,
                      "limit": 10                
                    },
                    "deliveryAddresses": [
                      {
                        "type": "BILLING",
                        "identifier":"deb89058-77fb-4e97-8c83-6506c3855555",
                        "address":"Main street 122",
                        "city":"San Francisco",
                        "state":"California",
                        "postalCode":"90210",
                        "recipient":"Jason Bourne",
                        "country":"US",
                        "secondaryAddress":null,
                        "mailStopCode":null,
                        "attention":null
                      }
                    ]
                  }
                  
        
      /{deliveryAddressId}:
        uriParameters:
          deliveryAddressId:
            type: common.resourceId
        type:
          collection.collectionMember:
            collectionMemberResponseType: customer.DeliveryAddressResponse
            collectionMemberPrototypeType: geography.PostalAddress
            
        get:
          responses: 
            200:
              body: 
                application/json:
                  example: |
                    {
                      "type": "BILLING",
                      "address": "Main street 122",
                      "city": "San Francisco",
                      "state": "California",
                      "postalCode": "90210",
                      "recipient": "Jason Bourne",
                      "country": "US",
                      "secondaryAddress": null,
                      "mailStopCode": null,
                      "attention": null
                    }
    /contactMethods:
      type:
        collection.collection:
          collectionResponseType: ContactMethodCollectionResponse
          collectionMemberPrototypeType: contact.ContactMethod
          collectionMemberResponseType: ContactMethodResponse
      get:
        is: *queryableCollection
        responses: 
          200:
            body: 
              application/json:
                example: | 
                  {
                    "_links": {
                      "self": {
                        "href": "https://mocksvc.mulesoft.com/mocks/226604b1-d88b-4e3b-8a5c-4c299e70db6c/customers/deb89058-77fb-4e97-8c83-6506c38cacf8/contactMethods"
                      }
                    },
                    "_meta": {
                      "messages": [],
                      "totalItems": 1,
                      "offset": 0,
                      "limit": 10                
                    },
                    "contactMethods": [
                      {
                        "contactMethodType": "EMAIL",
                        "emailAddress": "jason.bourne@example.com"
                      }
                    ]
                  }
      /{contactMethodId}:
        uriParameters:
          contactMethodId:
            type: common.resourceId
        type:
          collection.collectionMember:
            collectionMemberResponseType: ContactMethodResponse
            collectionMemberPrototypeType: contact.ContactMethod
        get:
          responses: 
            200:
              body: 
                application/json:
                  example: |
                    {
                      "contactMethodType": "EMAIL",
                      "emailAddress": "jason.bourne@example.com"
                    }
    /paymentMethods:
      type:
        collection.collection:
          collectionResponseType: customer.PaymentMethodCollectionResponse
          collectionMemberPrototypeType: payment.PaymentMethod
          collectionMemberResponseType: customer.PaymentMethodResponse
      get:
        is: *queryableCollection
        responses: 
          200:
            body: 
              application/json:
                example: |
                  {
                    "_links": {
                      "self": {
                        "href": "https://mocksvc.mulesoft.com/mocks/226604b1-d88b-4e3b-8a5c-4c299e70db6c/customers/deb89058-77fb-4e97-8c83-6506c38cacf8/paymentMethods"
                      }
                    },
                    "_meta": {
                      "messages": [],
                      "totalItems": 1,
                      "offset": 0,
                      "limit": 10                
                    },
                    "paymentMethods": [
                      {
                        "identifier":"deb89058-77fb-4e97-8c83-6506c38c4444",
                        "paymentMethodType":{  
                          "medium":"CARD",
                          "issuer":"BANK",
                          "name":"VISA"
                        }
                      }
                    ]
                  }
      /{paymentMethodId}:
        uriParameters:
          paymentMethodId:
            type: common.resourceId
        type:
          collection.collectionMember:
            collectionMemberResponseType: customer.PaymentMethodResponse
            collectionMemberPrototypeType: payment.PaymentMethod
        get:
          responses: 
            200:
              body: 
                application/json:
                  example: |
                    {
                      "identifier":"deb89058-77fb-4e97-8c83-6506c38c4444",
                      "paymentMethodType": {
                        "medium": "CARD",
                        "issuer": "BANK",
                        "name": "VISA"
                      }
                    }
    /orders:
      type:
        collection.readOnlyCollection:
          collectionResponseType: OrderCollectionResponse
      get:
        is: *queryableCollection
        responses: 
          200:
            body: 
              application/json:
                example: |
                  {
                    "_links": {
                      "self": {
                        "href": "https://mocksvc.mulesoft.com/mocks/226604b1-d88b-4e3b-8a5c-4c299e70db6c/customers/deb89058-77fb-4e97-8c83-6506c38cacf8/paymentMethods"
                      }
                    },
                    "_meta": {
                      "messages": [],
                      "totalItems": 1,
                      "offset": 0,
                      "limit": 10                
                    },
                    "orders": [
                        {
                          "orderId": "8010J0000022iETQAY",
                          "customerId": "951",
                          "price": "125.43",
                          "status": "Draft",
                          "trackingNumber": "8010J0000022iETQAY",
                          "orderItems": {
                            "pickupItems": [
                              {
                                "orderItemId": "88668866-2c6d-4fa6-9e17-4b2c42e0f051",
                                "productId": "eb8c8ca7-3c42-4489-a820-3aa138430b75",
                                "productName": "Smart Slim Micro Stripe Shirt",
                                "locationId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
                                "deliveryMethod": "PICKUP",
                                "price" : "50",
                                "quantity": 1
                              },
                              {
                                "orderItemId": "dfc25820-c37d-456c-8867-4a89a51b7f75",
                                "productId": "7c9be8ad-0791-4362-b195-a53dcca4e1d7",
                                "productName": "Men's Regular Fit V-Neck Knit Sweater",
                                "locationId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
                                "deliveryMethod": "PICKUP",
                                "price" : "60",
                                "quantity": 2
                              }
                            ],
                            "shipmentItems": [
                              {
                                "orderItemId": "3c1eb223-811c-4e86-8ea3-4a06a002a79a",
                                "productId": "cd67cd8a-8901-48c5-890b-0a21f4a0f8ad",
                                "productName": "Men's Chino Jogger Pants",
                                "locationId": "7307024a-7e63-11e7-bb31-be2e44b06b34",
                                "deliveryMethod": "SHIPMENT",
                                "price" : "30",
                                "quantity": 3
                              }
                            ],
                            "partnersItems": [
                              {
                                "orderItemId": "fc3d4900-c5ac-4649-8bc8-cbbef4fe8fde",
                                "productId": "e1c515f9-102d-4830-b353-18fe48065732",
                                "productName": "Uniforms Modern Fit Short Sleeve Polo Shirt",
                                "locationId": "730704d4-7e63-11e7-bb31-be2e44b06b34",
                                "deliveryMethod": "SHIPMENT",
                                "price" : "20",
                                "quantity": 1
                              }
                            ]
                          }
                        }
                      ]
                    }
                  
    /shoppingCarts:
      type:
        collection.readOnlyCollection:
          collectionResponseType: ShoppingCartCollectionResponse
      get:
        is: *queryableCollection
        responses:
          200:
            body: 
                application/json:
                  example: |
                      {
                          "_links": {
                              "self": {
                                "href": "https://mocksvc.mulesoft.com/mocks/226604b1-d88b-4e3b-8a5c-4c299e70db6c/customers/deb89058-77fb-4e97-8c83-6506c38cacf8/shoppingCarts"
                              }
                          },
                          "_meta": {
                            "messages": [],
                            "totalItems": 1,
                            "offset": 0,
                            "limit": 10                
                          },
                         "shoppingCarts": [
                                  {
                                    "identifier": "734a04dc-2f30-11e7-93ae-92361f002671",
                                    "customerId": "11e7-93ae-92361f002671",
                                    "items": [
                                      {
                                        "location": {
                                          "locationId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
                                          "deliveryMethod": "PICKUP",
                                          "locationType": "STORE"     
                                        },
                                        "item": {
                                          "productId": "eb8c8ca7-3c42-4489-a820-3aa138430b75",
                                          "identifier": "88668866-2c6d-4fa6-9e17-4b2c42e0f051"
                                        },
                                        "quantity": {
                                          "amount": 2,
                                          "quantityType": "DISCRETE",
                                          "unit": "EA"
                                        }
                                      }
                                    ]
                                  },
                                  {
                                    "identifier": "734a04dc-2f30-11e7-93ae-92361f002675",
                                    "customerId": "11e7-93ae-92361f002671",
                                    "items": [
                                      {
                                        "location": {
                                          "locationId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
                                          "deliveryMethod": "PICKUP",
                                          "locationType": "STORE"     
                                        },
                                        "item": {
                                          "productId": "eb8c8ca7-3c42-5489-a820-3aa138430b70",
                                          "identifier": "8866846-2c6d-4fa7-9e17-4b2c42e0f051" 
                                        },
                                        "quantity": {
                                          "amount": 1,
                                          "quantityType": "DISCRETE",
                                          "unit": "EA"
                                        }
                                      }
                                    ]
                                  }
                          ]
                       }

/channels:
  description: |
    Consists of the most common channels to cover use-cases with WEB, 
    mobile and brick-and-mortar(store) based application delivering the Omnichannel user experience.
  type:
    collection.readOnlyCollection:
      collectionResponseType: ChannelCollectionResponse
  get:
    is: &queryableCollection [ collection.pageable, collection.sortable ]
    queryParameters:
      paymentMedium?: payment.PaymentMediumType
      paymentIssuer?: payment.PaymentIssuerType
      receipt?: fulfillment.ReceiptType
      carrier?: fulfillment.CarrierType
    responses: 
      200:
        body: 
          application/json:
            example: |
              {
                "_links": {
                  "self": {
                    "href": "http://mocksvc.mulesoft.com/mocks/b97e9f37-a930-4f88-bd72-d3f8ac7dfda2/channels"
                  }
                },
                "_meta": {
                  "messages": [],
                  "totalItems": 3,
                  "offset": 0,
                  "limit": 10                
                },
                "channels": [
                  {
                    "channelType": "WEB",
                    "url": "http://www.example.com"
                  },
                  {
                    "channelType": "STORE",
                    "storeNumber": "ae42643a-6d19-483c-82a2-54939d9da13e"
                  },
                  {
                    "channelType": "MOBILE",
                    "name": "iOS"
                  }
                ]
              }
  /{channelId}:
    uriParameters:
      channelId: common.resourceId
    type:
       collection.readOnlyCollectionMember:
         collectionMemberResponseType: ChannelResponse
    get: 
      responses: 
        200:
          body: 
            application/json:
              example: |
                {
                  "channelType": "WEB",
                  "url": "http://www.example.com"
                }
    /paymentMethods:
      description: |
        Channel basically could have different payment methods according to channel type like VISA card, bank transfer, cash. 
      type:
        collection.readOnlyCollection:
          collectionResponseType: customer.PaymentMethodCollectionResponse
      get:
        is: *queryableCollection
        queryParameters:
          paymentMedium: payment.PaymentMediumType
          paymentIssuer: payment.PaymentIssuerType         
        responses: 
          200:
            body: 
              application/json:
                example: |
                  {
                    "_links": {
                      "self": {
                        "href": "http://mocksvc.mulesoft.com/mocks/b97e9f37-a930-4f88-bd72-d3f8ac7dfda2/channels/deb89058-77fb-4e97-8c83-6506c38cacf8/products?offset=0&limit=5"
                      }
                    },
                    "_meta": {
                      "messages": [],
                      "totalItems": 1,
                      "offset": 0,
                      "limit": 5                
                    },
                    "paymentMethods": [
                         {
                            "paymentMethodType": {
                              "cash": {
                                "medium": "PHYSICAL",
                                "issuer": "GOVT",
                                "name": "CASH"
                              }
                            }
                         },
                         {
                            "paymentMethodType": {
                              "check": {
                                "medium": "PHYSICAL",
                                "issuer": "BANK",
                                "name": "CHECK"
                              }
                            }
                         },
                         {
                            "paymentMethodType": {
                              "visa": {
                                "medium": "CARD",
                                "issuer": "BANK",
                                "name": "VISA"
                              }
                            }
                         }
                    ]
                  }
                
    /fulfillmentMethods:
      type:
        collection.readOnlyCollection:
          collectionResponseType: FulfillmentMethodCollectionResponse
      get:
        is: *queryableCollection
        queryParameters:
          receipt: fulfillment.ReceiptType
          carrier: fulfillment.CarrierType
        responses:
          200:
            body: 
              application/json:
                example: |
                  {
                    "_links": {
                      "self": {
                        "href": "http://mocksvc.mulesoft.com/mocks/b97e9f37-a930-4f88-bd72-d3f8ac7dfda2/channels/deb89058-77fb-4e97-8c83-6506c38cacf8/products?offset=0&limit=5"
                      }
                    },
                    "_meta": {
                      "messages": [],
                      "totalItems": 1,
                      "offset": 0,
                      "limit": 5                
                    },
                    "fulfillmentMethods": [
                      { 
                        "carrier": "POSTAL",
                        "deliveryAddress": {
                            "type": "SHIPPING",
                            "address": "Main street 122",
                            "city": "San Francisco",
                            "state": "California",
                            "postalCode": "90210",
                            "recipient": "Jason Bourne",
                            "country": "US",
                            "secondaryAddress": null,
                            "mailStopCode": null,
                            "attention": null
                        },
                      "receipt": "PICKUP"
                      }
                    ]
                  }
    /products:
      type:
        collection.readOnlyCollection:
          collectionResponseType: ProductCollectionResponse
      get:
        is: *queryableCollection
        queryParameters:
          name?: string
          minPrice?: integer
          maxPrice?: integer
        responses:
          200:
            body:
              application/json:
                example: |
                  {
                    "_links": {
                      "self": {
                        "href": "http://mocksvc.mulesoft.com/mocks/b97e9f37-a930-4f88-bd72-d3f8ac7dfda2/channels/deb89058-77fb-4e97-8c83-6506c38cacf8/products?offset=0&limit=5"
                      }
                    },
                    "_meta": {
                      "messages": [],
                      "totalItems": 1,
                      "offset": 0,
                      "limit": 5                
                    },
                    "products": [
                      {
                        "brand": "Anypoint",
                        "identifier": "eb8c8ca7-3c42-4489-a820-3aa138430b75",
                        "categoryId" : ["5e5b095e-8b60-429c-98bf-da36afeb1f1c"],
                        "identifiers": {
                          "SKU": "UGG-BB-PUR-06"
                        },
                        "model": "Smart Slim Micro Stripe Shirt",
                        "rating": 5,
                        "description": "Shirt by ASOS Tall. Stripe woven fabric. Added stretch for comfort. Spread collar. Button placket. Slim fit - cut close to the body. Machine wash. 98% Cotton, 2% Elastane. Our model wears a size Medium Long and is 193cm/6'4\" tall",
                        "pictures": [
                          "https://launderkart.com/wp-content/uploads/2016/07/Shirt.jpg",
                          "https://cdni.llbean.net/is/image/wim/251423_47_41?wid=428&hei=494"
                        ],
                        "price": {
                          "amount": {
                            "currency": "USD",
                            "currencyValue": 34.90,
                            "name": "Amount"
                          },
                           "salesUnit": {
                            "code": "EA",
                            "name": "Each"
                          }
                        }
                      }
                    ]
                  }
    /categories:
      type:
        collection.readOnlyCollection:
          collectionResponseType: CategoryCollectionResponse
      get:
        is: *queryableCollection
        responses: 
          200:
            body: 
              application/json:
                example: |
                  {
                    "_links": {
                      "self": {
                        "href": "http://mocksvc.mulesoft.com/mocks/b97e9f37-a930-4f88-bd72-d3f8ac7dfda2/categories/deb89058-77fb-4e97-8c83-6506c38cacf8/products?offset=0&limit=5"
                      }
                    },
                    "_meta": {
                      "messages": [],
                      "totalItems": 5,
                      "offset": 0,
                      "limit": 5                
                    },
                    "categories": [
                      {
                          
                          "identifier": "fe3d0325-be8c-45b8-aa96-2331f25542be",
                          "name": "Sweaters",
                          "description": "Sweaters"
                      },
                      {
                          
                          "identifier": "d3d0d1fd-b33c-4d40-b559-04665aa9ead6",
                          "name": "Hats",
                          "description": "Hats"
                      },
                      {     
                          "identifier": "5e5b095e-8b60-429c-98bf-da36afeb1f1c",
                          "name": "Shirts",
                          "description": "Shirts"
                      }
                    ]
                  }

/categories:
  type:
    collection.readOnlyCollection:
      collectionResponseType: CategoryCollectionResponse
  get:
    is: *queryableCollection
    responses: 
      200:
        body: 
          application/json:
            example: |
              {
                "_links": {
                  "self": {
                    "href": "http://mocksvc.mulesoft.com/mocks/b97e9f37-a930-4f88-bd72-d3f8ac7dfda2/categories/deb89058-77fb-4e97-8c83-6506c38cacf8/products?offset=0&limit=5"
                  }
                },
                "_meta": {
                  "messages": [],
                  "totalItems": 5,
                  "offset": 0,
                  "limit": 5                
                },
                "categories": [
                      {
                          "identifier": "49ed1d7f-9583-40aa-8e80-bfea709b16a4",
                          "name": "Most popular items",
                          "description": "Most popular items",
                          "abstract": true
                      },
                      {
                          "identifier": "fe3d0325-be8c-45b8-aa96-2331f25542be",
                          "name": "Sweaters",
                          "description": "Sweaters"
                      },
                      {
                          "identifier": "d3d0d1fd-b33c-4d40-b559-04665aa9ead6",
                          "name": "Jeans",
                          "description": "Jeans"
                      },
                      {     
                          "identifier": "5e5b095e-8b60-429c-98bf-da36afeb1f1c",
                          "name": "Shirts",
                          "description": "Shirts"
                      },
                      {   "parentId" : "49ed1d7f-9583-40aa-8e80-bfea709b16a4",  
                          "identifier": "67912d0b-1dfa-4a62-a552-f0d01d5b0c79",
                          "name": "Hats",
                          "description": "Hats"
                      },
                      {   
                          "parentId" : "49ed1d7f-9583-40aa-8e80-bfea709b16a4",  
                          "identifier": "c9032941-b3a5-4e8e-8134-baee3a751eb9",
                          "name": "Shoes",
                          "description": "Shoes"
                      }
                    ]
                  }
  /{categoryId}:
    uriParameters:
      categoryId: string
    type:
       collection.readOnlyCollectionMember:
         collectionMemberResponseType: CategoryResponse
    get:
      responses: 
        200:
          body: 
            application/json:
              example: |
                {
                    "parentId" : "49ed1d7f-9583-40aa-8e80-bfea709b16a4",
                    "identifier": "5e5b095e-8b60-429c-98bf-da36afeb1f1c",
                    "name": "Shirts",
                    "description": "Shirts"
                }
                
    /products:
      type:
        collection.readOnlyCollection:
          collectionResponseType: ProductCollectionResponse
      get:
        is: *queryableCollection
        queryParameters:
            name?: string
            minPrice?: integer
            maxPrice?: integer
        responses:
          200:
            body:
              application/json:
                example: |
                  {
                    "_links": {
                      "self": {
                        "href": "http://mocksvc.mulesoft.com/mocks/b97e9f37-a930-4f88-bd72-d3f8ac7dfda2/categories/b625ea67-e23f-46d2-be6a-653de1f620a8/products?offset=0&limit=5"
                      }
                    },
                    "_meta": {
                      "messages": [],
                      "totalItems": 1,
                      "offset": 0,
                      "limit": 5              
                    },
                    "products":[  
                        {  
                           "brand":"Anypoint",
                           "identifier":"eb8c8ca7-3c42-4489-a820-3aa138430b75",
                           "categoryId": ["5e5b095e-8b60-429c-98bf-da36afeb1f1c"],
                           "model":"Smart Slim Micro Stripe Shirt",
                           "rating":5,
                           "description":"Shirt by ASOS Tall. Stripe woven fabric. Added stretch for comfort. Spread collar. Button placket. Slim fit - cut close to the body. Machine wash. 98% Cotton, 2% Elastane. Our model wears a size Medium Long and is 193cm/6'4\" tall",
                           "pictures":[  
                              "https://cdni.llbean.net/is/image/wim/251423_0_52??wid=428&hei=494",
                              "https://cdni.llbean.net/is/image/wim/251423_47_41?wid=428&hei=494"
                           ],
                           "price":{  
                              "amount":{  
                                 "currency":"USD",
                                 "currencyValue":34.90,
                                 "name":"Amount"
                              },
                              "salesUnit":{  
                                 "code":"EA",
                                 "name":"Each"
                              }
                           }
                        },
                        {  
                           "brand":"Anypoint",
                           "identifier":"e1c515f9-102d-4830-b353-18fe48065732",
                           "categoryId" : ["5e5b095e-8b60-429c-98bf-da36afeb1f1c"],
                           "model":"Uniforms Modern Fit Short Sleeve Polo Shirt",
                           "rating":5,
                           "description":"Machine Wash, Tumble Dry. True to Size.",
                           "pictures":[  
                              "https://images-na.ssl-images-amazon.com/images/I/41p0XBBb6vL.jpg"
                           ],
                           "price":{  
                              "amount":{  
                                 "currency":"USD",
                                 "currencyValue":12.95,
                                 "name":"Amount"
                              },
                              "salesUnit":{  
                                 "code":"EA",
                                 "name":"Each"
                              }
                           }
                        }
                     ]
                  }
/stores:
  type:
    collection.readOnlyCollection:
      collectionResponseType: StoreCollectionResponse
  get:
    is: *queryableCollection
    queryParameters:
      paymentMedium?: payment.PaymentMediumType
      paymentIssuer?: payment.PaymentIssuerType
      receipt?: fulfillment.ReceiptType
      carrier?: fulfillment.CarrierType
    responses:
      200:
        body:
          application/json:
            example: | 
               {  
                  "_links": {
                    "self": {
                      "href": "http://mocksvc.mulesoft.com/mocks/b97e9f37-a930-4f88-bd72-d3f8ac7dfda2/stores?offset=0&limit=5"
                    }
                  },
                  "_meta": {
                    "messages": [],
                    "totalItems": 1,
                    "offset": 0,
                    "limit": 5              
                  },
                 "stores": [
                    {
                      "storeId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
                      "name": "Anypoint Store 1",
                      "description": "Department store chain providing brand-name c",
                      "notes": "Department store chain providing brand-name c",
                      "openingHours": "Mo,Tu,We,Th,Fr 09:00-20:00",
                      "address": {
                        "streetLine1": "170 O'Farrell St",
                        "streetLine2": "",
                        "city": "San Francisco",
                        "zipCode": "94102",
                        "state": "California",
                        "country": "USA"
                      },
                      "contact": {
                        "email": "store1@anypointstore.example.com",
                        "phone": "+1-202-555-0111"
                      },
                      "geo": {
                        "latitude": 37.78703308105469,
                        "longitude": -122.4060287475586
                      }
                    } 
                 ]
               }
  /{storeId}:
    uriParameters:
      storeId: string
    type:
       collection.readOnlyCollectionMember:
         collectionMemberResponseType: StoreResponse
    get: 
      responses:
        200:
          body:
            application/json:
              example: |
                  {
                    "storeId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
                    "name": "Anypoint Store 1",
                    "description": "Department store chain providing brand-name c",
                    "notes": "Department store chain providing brand-name c",
                    "openingHours": "Mo,Tu,We,Th,Fr 09:00-20:00",
                    "address": {
                      "streetLine1": "170 O'Farrell St",
                      "streetLine2": "",
                      "city": "San Francisco",
                      "zipCode": "94102",
                      "state": "California",
                      "country": "USA"
                    },
                    "contact": {
                      "email": "store1@anypointstore.example.com",
                      "phone": "+1-202-555-0111"
                    },
                    "geo": {
                      "latitude": 37.78703308105469,
                      "longitude": -122.4060287475586
                    }
                  }     
    /paymentMethods:
      type:
        collection.readOnlyCollection:
          collectionResponseType: customer.PaymentMethodCollectionResponse
      get:
        is: *queryableCollection
        queryParameters:
          paymentMedium: payment.PaymentMediumType
          paymentIssuer: payment.PaymentIssuerType
    /fulfillmentMethods:
      type:
        collection.readOnlyCollection:
          collectionResponseType: FulfillmentMethodCollectionResponse
      get:
        is: *queryableCollection
        queryParameters:
          receipt: fulfillment.ReceiptType
          carrier: fulfillment.CarrierType
    /products:
      type:
        collection.readOnlyCollection:
          collectionResponseType: ProductCollectionResponse
      get:
        is: *queryableCollection
    /categories:
      type:
        collection.readOnlyCollection:
          collectionResponseType: ProductCollectionResponse
      get:
        is: *queryableCollection
    /nearbyStores:
      type:
        collection.readOnlyCollection:
          collectionResponseType: StoreCollectionResponse
      get:
        is: *queryableCollection
        queryParameters:
          radius:
            type: number
            default: 5
            minimum: 0.5
            maximum: 50
            required: true

/partners: 
  type: 
    collection.readOnlyCollection:
      collectionResponseType: PartnerCollectionResponse
  get: 
    is: *queryableCollection 
    responses:
      200:
        body:
          application/json:
            example: | 
               {  
                  "_links": {
                    "self": {
                      "href": "http://mocksvc.mulesoft.com/mocks/b97e9f37-a930-4f88-bd72-d3f8ac7dfda2/stores?offset=0&limit=5"
                    }
                  },
                  "_meta": {
                    "messages": [],
                    "totalItems": 1,
                    "offset": 0,
                    "limit": 5              
                  },
                 "partners": [
                      {
                        "partnerId": "2d9df8be-a185-4dde-9577-d6edf6cdb398",
                        "name": "Best Amazing Store",
                        "description": "",
                        "email": "info@luckystore.example.com",
                        "phone": "+1-202-555-0119",
                        "url": "www.luckystore.example.com",
                        "shippingPrice": 5.5,
                        "rating": 4
                      },
                      {
                        "partnerId": "84c95f82-c435-4de0-8964-82e16bd23689",
                        "name": "Shop For You",
                        "description": "",
                        "email": "info@shopforyou.example.com",
                        "phone": "+1-202-555-0146",
                        "url": "www.shopforyou.example.com",
                        "shippingPrice": 7.5,
                        "rating": 4
                      }
                    ]
                 }
  /{partnerId}:
    uriParameters:
      partnerId: string
    type:
       collection.readOnlyCollectionMember:
         collectionMemberResponseType: PartnerResponse
    get: 
      responses:
        200:
          body:
            application/json:
              example: |
                  {
                    "partnerId": "2d9df8be-a185-4dde-9577-d6edf6cdb398",
                    "name": "Best Amazing Store",
                    "description": "",
                    "email": "info@luckystore.example.com",
                    "phone": "+1-202-555-0119",
                    "url": "www.luckystore.example.com",
                    "shippingPrice": 5.5,
                    "rating": 4
                  }
/orders:
  type:
    collection.collection:
      collectionResponseType: SalesOrderCollectionResponse
      collectionMemberPrototypeType: order.SalesOrder
      collectionMemberResponseType: SalesOrderResponse
  get:
    is: &queryableCollection [ collection.pageable, collection.sortable ]
    responses: 
      200:
        body: 
          application/json:
            example: |
              {
                "_links": {
                  "self": {
                    "href": "https://mocksvc.mulesoft.com/mocks/226604b1-d88b-4e3b-8a5c-4c299e70db6c/orders"
                  }
                },
                "_meta": {
                  "messages": []
                },
                "orders": [
                  {
                    "customerId": "deb89058-77fb-4e97-8c83-6506c38cacf8",
                    "orderItems": [
                      {
                        "quantity": {
                          "quantityType": "DISCRETE",
                          "unit": "EA",
                          "amount": 1
                        },
                        "location": {
                              "locationId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
                              "deliveryMethod": "PICKUP",
                              "locationType": "STORE"     
                        }, 
                        "item": {
                          "identifier": "88668866-2c6d-4fa6-9e17-4b2c42e0f051",
                          "productId": "eb8c8ca7-3c42-4489-a820-3aa138430b75",
                          "identifiers": {
                            "SKU": "UGG-BB-PUR-06"
                          }
                        },
                        "itemUnitPrice": {
                          "amount": {
                            "currency": "USD",
                            "currencyValue": 34.9,
                            "name": "Amount"
                          },
                          "salesUnit": {
                            "code": "EA",
                            "name": "Each"
                          }
                        }
                      }
                    ]
                  }
                ]
              }
  post:
    body: 
      application/json:
        example: |
            {
              "customerId": "facebook_1234567890123456",
              "fulfillment": {
                "receipt": "SHIPMENT",
                "carrier": "POSTAL",
                "deliveryAddress": {
                  "type": "SHIPPING"
                }
              },
              "orderItems": [
                {
                  "quantity": {
                    "quantityType": "DISCRETE",
                    "unit": "EA",
                    "amount": 1
                  },
                  "location": {
                              "locationId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
                              "deliveryMethod": "PICKUP",
                              "locationType": "STORE"     
                  }, 
                  "item": {
                    "configuration": [
                      {
                        "characteristic": {
                          "code": "size",
                          "description": "Size",
                          "name": "Size of item"
                        },
                        "characteristicValue": {
                          "code": "M",
                          "name": "Medium"
                        }
                      },
                      {
                        "characteristic": {
                          "code": "color",
                          "description": "Color",
                          "name": "Color"
                        },
                        "characteristicValue": {
                          "code": "blue",
                          "name": "Blue"
                        }
                      }
                    ],
                    "identifier": "88668866-2c6d-4fa6-9e17-4b2c42e0f051",
                    "productId": "eb8c8ca7-3c42-4489-a820-3aa138430b75",
                    "identifiers": {
                      "SKU": "UGG-BB-PUR-06"
                    },
                    "pictures": [
                      "https://cdni.llbean.net/is/image/wim/251423_0_52??wid=428&hei=494",
                      "https://cdni.llbean.net/is/image/wim/251423_47_41?wid=428&hei=494"
                    ],
                    "color": "Blue",
                    "size": "Medium"
                  },
                  "itemUnitPrice": {
                    "amount": {
                      "currency": "USD",
                      "currencyValue": 34.9,
                      "name": "Amount"
                    },
                    "salesUnit": {
                      "code": "EA",
                      "name": "Each"
                    }
                  },
                  "itemExtendedPrice": {
                    "currency": "USD",
                    "currencyValue": 34.9,
                    "name": "Amount"
                  }
                },
                {
                  "quantity": {
                    "quantityType": "DISCRETE",
                    "unit": "EA",
                    "amount": 1
                  },
                  "location": {
                      "locationId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
                      "deliveryMethod": "PICKUP",
                      "locationType": "STORE"     
                  }, 
                  "item": {
                    "configuration": [
                      {
                        "characteristic": {
                          "code": "size",
                          "description": "Size",
                          "name": "Size of item"
                        },
                        "characteristicValue": {
                          "code": "L",
                          "name": "Large"
                        }
                      },
                      {
                        "characteristic": {
                          "code": "color",
                          "description": "Color",
                          "name": "Color"
                        },
                        "characteristicValue": {
                          "code": "tan",
                          "name": "Tan"
                        }
                      }
                    ],
                    "identifier": "355d4130-1e3a-4795-aada-c960c89f6d9f",
                    "productId": "cd67cd8a-8901-48c5-890b-0a21f4a0f8ad",
                    "identifiers": {
                      "SKU": "UGG-BB-PUR-06"
                    },
                    "pictures": [
                      "https://images-na.ssl-images-amazon.com/images/I/61Ezqhc-8AL._UX342_.jpg"
                    ],
                    "color": "Tan",
                    "size": "Large"
                  },
                  "itemUnitPrice": {
                    "amount": {
                      "currency": "USD",
                      "currencyValue": 47.95,
                      "name": "Amount"
                    },
                    "salesUnit": {
                      "code": "EA",
                      "name": "Each"
                    }
                  },
                  "itemExtendedPrice": {
                    "currency": "USD",
                    "currencyValue": 47.95,
                    "name": "Amount"
                  }
                }
              ]
            }
    responses: 
      201:
        body: 
          application/json:
            example: |
              {
                "customerId": "deb89058-77fb-4e97-8c83-6506c38cacf8",
                "orderItems" : [
                    {
                      "identifier" : "88668866-2c6d-4fa6-9e17-4b2c42e0f051",
                      "productId" : "eb8c8ca7-3c42-4489-a820-3aa138430b75"
                    }
                ],
                "fulfillment": {
                  "carrier": "POSTAL",
                  "deliveryAddress": {
                    "type": "SHIPPING",
                    "address": "Main street 122",
                    "city": "San Francisco",
                    "state": "California",
                    "postalCode": "90210",
                    "recipient": "Jason Bourne",
                    "country": "US",
                    "secondaryAddress": null,
                    "mailStopCode": null,
                    "attention": null
                  },
                  "receipt": "PICKUP"
                }
              }
  /{salesOrderId}:
    uriParameters:
      salesOrderId:
        type: string
    type:
      collection.collectionMember:
        collectionMemberResponseType: SalesOrderResponse
        collectionMemberPrototypeType: order.SalesOrder
    get:
      responses: 
        200:
          body: 
            application/json:
              example: |
                {
                  "identifier" : "a41534afb0bada55",
                  "customerId": "deb89058-77fb-4e97-8c83-6506c38cacf8",
                  "fulfillment": {
                    "receipt": "SHIPMENT",
                    "carrier": "POSTAL",
                    "deliveryAddress": {
                        "type": "SHIPPING",
                        "address": "Main street 122",
                        "city": "San Francisco",
                        "state": "California",
                        "postalCode": "90210",
                        "recipient": "Jason Bourne",
                        "country": "US",
                        "secondaryAddress": null,
                        "mailStopCode": null,
                        "attention": null
                      }
                  },
                  "orderItems": [
                    {
                      "quantity": {
                        "quantityType": "DISCRETE",
                        "unit": "EA",
                        "amount": 1
                      },
                      "item": {
                        "identifier": "88668866-2c6d-4fa6-9e17-4b2c42e0f051",
                        "productId": "eb8c8ca7-3c42-4489-a820-3aa138430b75",
                        "identifiers": {
                          "SKU": "UGG-BB-PUR-06"
                        }
                      },
                      "itemUnitPrice": {
                        "amount": {
                          "currency": "USD",
                          "currencyValue": 34.9,
                          "name": "Amount"
                        },
                        "salesUnit": {
                          "code": "EA",
                          "name": "Each"
                        }
                      }
                    }
                  ]
                }
    put:
      responses: 
        200:
          body: 
            application/json:
              example: |
                {
                  "identifier" : "a41534afb0bada55",
                  "customerId": "deb89058-77fb-4e97-8c83-6506c38cacf8",
                  "fulfillment": {
                    "receipt": "SHIPMENT",
                    "carrier": "POSTAL",
                    "deliveryAddress": {
                        "type": "SHIPPING",
                        "address": "Main street 122",
                        "city": "San Francisco",
                        "state": "California",
                        "postalCode": "90210",
                        "recipient": "Jason Bourne",
                        "country": "US",
                        "secondaryAddress": null,
                        "mailStopCode": null,
                        "attention": null
                      }
                  },
                  "orderItems": [
                    {
                      "quantity": {
                        "quantityType": "DISCRETE",
                        "unit": "EA",
                        "amount": 1
                      },
                      "item": {
                        "identifier": "88668866-2c6d-4fa6-9e17-4b2c42e0f051",
                        "productId": "eb8c8ca7-3c42-4489-a820-3aa138430b75",
                        "identifiers": {
                          "SKU": "UGG-BB-PUR-06"
                        }
                      },
                      "itemUnitPrice": {
                        "amount": {
                          "currency": "USD",
                          "currencyValue": 34.9,
                          "name": "Amount"
                        },
                        "salesUnit": {
                          "code": "EA",
                          "name": "Each"
                        }
                      }
                    }
                  ]
                }
    delete:
      responses: 
        200:
          body: 
            application/json:
              example: |
                {
                  "_meta": {
                    "messages": []
                  }
                }
    /paymentMethod:
      type:
        collection.updatableCollectionMember:
          collectionMemberPrototypeType: payment.PaymentMethod
          collectionMemberResponseType: SalesOrderPaymentMethodResponse
      get:
        responses: 
          200:
            body: 
              application/json:
                example: |
                  {
                    "paymentMethodType": {
                        "medium": "CARD",
                        "issuer": "BANK",
                        "name": "VISA"
                      }
                  }
      put:
        responses: 
          200:
            body: 
              application/json:
                example: |
                  {
                    "paymentMethodType": {
                        "medium": "CARD",
                        "issuer": "BANK",
                        "name": "VISA"
                      }
                  }
    /fulfillment:
      type:
        collection.updatableCollectionMember:
          collectionMemberPrototypeType: fulfillment.Fulfillment
          collectionMemberResponseType: SalesOrderFulfillmentResponse
      get:
        responses: 
          200:
            body: 
              application/json:
                example: |
                  {
                    "carrier": "POSTAL",
                    "deliveryAddress": {
                        "type": "SHIPPING",
                        "address": "Main street 122",
                        "city": "San Francisco",
                        "state": "California",
                        "postalCode": "90210",
                        "recipient": "Jason Bourne",
                        "country": "US",
                        "secondaryAddress": null,
                        "mailStopCode": null,
                        "attention": null
                    },
                    "receipt": "PICKUP"
                  }
      put:
        responses: 
          200:
            body: 
              application/json:
                example: |
                  {
                    "carrier": "POSTAL",
                    "deliveryAddress": {
                        "type": "SHIPPING",
                        "address": "Main street 122",
                        "city": "San Francisco",
                        "state": "California",
                        "postalCode": "90210",
                        "recipient": "Jason Bourne",
                        "country": "US",
                        "secondaryAddress": null,
                        "mailStopCode": null,
                        "attention": null
                    },
                    "receipt": "PICKUP"
                  }
    /orderItems:
      type:
        collection.updatableCollectionMember:
          collectionMemberPrototypeType: order.SalesOrderItems
          collectionMemberResponseType: SalesOrderItemCollectionResponse
      get:
        responses: 
          200:
            body: 
              application/json:
                example: |
                  {
                    "_links": {
                      "self": {
                        "href": "https://mocksvc.mulesoft.com/mocks/226604b1-d88b-4e3b-8a5c-4c299e70db6c/orders/3bafde00-2eab-11e7-93ae-92361f002671/orderItems"
                      }
                    },
                    "orderItems": [
                      {
                        "location": {
                              "locationId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
                              "deliveryMethod": "PICKUP",
                              "locationType": "STORE"     
                        }, 
                        "item": {
                          "configuration": [
                            {
                              "characteristic": {
                                "code": "size",
                                "description": "Size",
                                "name": "Size of item"
                              },
                              "characteristicValue": {
                                "code": "M",
                                "name": "Medium"
                              }
                            },
                            {
                              "characteristic": {
                                "code": "color",
                                "name": "Color",
                                "description": "Color"
                              },
                              "characteristicValue": {
                                "code": "blue",
                                "name": "Blue"
                              }
                            }
                          ],
                          "productId": "eb8c8ca7-3c42-4489-a820-3aa138430b75",
                          "identifier": "88668866-2c6d-4fa6-9e17-4b2c42e0f051",
                          "identifiers": {
                            "SKU": "UGG-BB-PUR-06"
                          }
                        },
                        "itemExtendedPrice": {
                          "currency": "EUR",
                          "currencyValue": 31.93,
                          "name": "Amount"
                        },
                        "itemUnitPrice": {
                          "amount": {
                            "currency": "USD",
                            "currencyValue": 34.90,
                            "name": "Amount"
                          },
                          "salesUnit": {
                            "code": "EA",
                            "name": "Each"
                          }
                        },
                        "quantity": {
                          "amount": 2,
                          "quantityType": "CONTINUOUS",
                          "unit": "EA"
                        }
                      }
                    ]
                  }
      put:
        responses: 
          200:
            body: 
              application/json:
                example: |
                  {
                    "_links": {
                      "self": {
                        "href": "https://mocksvc.mulesoft.com/mocks/226604b1-d88b-4e3b-8a5c-4c299e70db6c/orders/3bafde00-2eab-11e7-93ae-92361f002671/orderItems"
                      }
                    },
                    "orderItems": [
                      {
                        "location": {
                              "locationId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
                              "deliveryMethod": "PICKUP",
                              "locationType": "STORE"     
                        }, 
                        "item": {
                          "configuration": [
                            {
                              "characteristic": {
                                "code": "size",
                                "description": "Size",
                                "name": "Size of item"
                              },
                              "characteristicValue": {
                                "code": "M",
                                "name": "Medium"
                              }
                            },
                            {
                              "characteristic": {
                                "code": "color",
                                "name": "Color",
                                "description": "Color"
                              },
                              "characteristicValue": {
                                "code": "blue",
                                "name": "Blue"
                              }
                            }
                          ],
                          "productId": "eb8c8ca7-3c42-4489-a820-3aa138430b75",
                          "identifier": "88668866-2c6d-4fa6-9e17-4b2c42e0f051",
                          "identifiers": {
                            "SKU": "UGG-BB-PUR-06"
                          }
                        },
                        "itemExtendedPrice": {
                          "currency": "EUR",
                          "currencyValue": 31.93,
                          "name": "Amount"
                        },
                        "itemUnitPrice": {
                          "amount": {
                            "currency": "USD",
                            "currencyValue": 34.90,
                            "name": "Amount"
                          },
                          "salesUnit": {
                            "code": "EA",
                            "name": "Each"
                          }
                        },
                        "quantity": {
                          "amount": 2,
                          "quantityType": "CONTINUOUS",
                          "unit": "EA"
                        }
                      }
                    ]
                  }


/products:
  type:
    collection.readOnlyCollection:
      collectionResponseType: ProductCollectionResponse
  get:
    is: &queryableCollection [ collection.pageable, collection.sortable ]
    queryParameters: 
      name?: string
    responses: 
      200:
        body: 
          application/json:
            example: |
              {
                "_links": {
                  "self": {
                    "href": "https://mocksvc.mulesoft.com/mocks/226604b1-d88b-4e3b-8a5c-4c299e70db6c/products?offset=0&limit=5"
                  }
                },
                "_meta": {
                  "messages": [],
                  "totalItems": 1,
                  "offset": 0,
                  "limit": 5                
                },
                "products": [
                      {
                        "brand": "Anypoint",
                        "identifier": "eb8c8ca7-3c42-4489-a820-3aa138430b75",
                        "categoryId" : ["5e5b095e-8b60-429c-98bf-da36afeb1f1c"],
                        "identifiers": {
                          "SKU": "UGG-BB-PUR-06"
                        },
                        "model": "Smart Slim Micro Stripe Shirt",
                        "rating": 5,
                        "description": "Shirt by ASOS Tall. Stripe woven fabric. Added stretch for comfort. Spread collar. Button placket. Slim fit - cut close to the body. Machine wash. 98% Cotton, 2% Elastane. Our model wears a size Medium Long and is 193cm/6'4\" tall",
                        "pictures": [
                          "https://launderkart.com/wp-content/uploads/2016/07/Shirt.jpg",
                          "https://cdni.llbean.net/is/image/wim/251423_47_41?wid=428&hei=494"
                        ],
                        "price": {
                          "amount": {
                            "currency": "USD",
                            "currencyValue": 34.90,
                            "name": "Amount"
                          },
                           "salesUnit": {
                            "code": "EA",
                            "name": "Each"
                          }
                        }
                      }
                    ]
                  }
  /{productId}:
    uriParameters:
      productId: string
    type:
       collection.readOnlyCollectionMember:
         collectionMemberResponseType: ProductResponse
    get:
      responses: 
        200:
          body:
            application/json:
              example: |
                {
                  "brand": "Anypoint",
                  "identifier": "eb8c8ca7-3c42-4489-a820-3aa138430b75",
                  "categoryId" : ["5e5b095e-8b60-429c-98bf-da36afeb1f1c"],
                  "identifiers": {
                    "SKU": "UGG-BB-PUR-06"
                  },
                  "model": "Smart Slim Micro Stripe Shirt",
                  "rating": 5,
                  "description": "Shirt by ASOS Tall. Stripe woven fabric. Added stretch for comfort. Spread collar. Button placket. Slim fit - cut close to the body. Machine wash. 98% Cotton, 2% Elastane. Our model wears a size Medium Long and is 193cm/6'4\" tall",
                  "pictures": [
                    "https://launderkart.com/wp-content/uploads/2016/07/Shirt.jpg",
                    "https://cdni.llbean.net/is/image/wim/251423_47_41?wid=428&hei=494"
                  ],
                  "price": {
                    "amount": {
                      "currency": "USD",
                      "currencyValue": 34.90,
                      "name": "Amount"
                    },
                     "salesUnit": {
                      "code": "EA",
                      "name": "Each"
                    }
                  }
                }
           
    /features:
      type:
        collection.readOnlyCollection:
          collectionResponseType: FeatureCollectionResponse
      get:
        is: &queryableCollection [ collection.pageable, collection.sortable ]
        
      /{featureId}:
        uriParameters:
          featureId: common.resourceId
        type:
           collection.readOnlyCollectionMember:
             collectionMemberResponseType: FeatureResponse
             
             
    /variants:
      type:
        collection.readOnlyCollection:
          collectionResponseType: ProductVariantCollectionResponse
      get:
        is: &queryableCollection [ collection.pageable, collection.sortable ]
        responses: 
          200:
            body: 
              application/json:
                example: |
                  {
                    "_links": {
                      "self": {
                        "href": "https://mocksvc.mulesoft.com/mocks/226604b1-d88b-4e3b-8a5c-4c299e70db6c/products/eb8c8ca7-3c42-4489-a820-3aa138430b75/variants"
                      }
                    },
                    "_meta": {
                      "messages": [],
                      "offset": 0,
                      "limit": 10,
                      "totalItems": 1
                    },
                    "variants":[  
                      {  
                         "productId":"eb8c8ca7-3c42-4489-a820-3aa138430b75",
                         "identifier":"88668866-2c6d-4fa6-9e17-4b2c42e0f051",
                         "identifiers":{  
                            "SKU":"UGG-BB-PUR-06"
                         },
                         "pictures":[  
                            "https://cdni.llbean.net/is/image/wim/251423_0_52??wid=428&hei=494",
                            "https://cdni.llbean.net/is/image/wim/251423_47_41?wid=428&hei=494"
                         ],
                         "configuration":[  
                            {  
                               "characteristic":{  
                                  "code":"size",
                                  "description":"Size",
                                  "name":"Size of item"
                               },
                               "characteristicValue":{  
                                  "code":"M",
                                  "name":"Medium"
                               }
                            },
                            {  
                               "characteristic":{  
                                  "code":"color",
                                  "description":"Color",
                                  "name":"Color"
                               },
                               "characteristicValue":{  
                                  "code":"blue",
                                  "name":"Blue"
                               }
                            }
                         ]
                      }
                    ]
                  }
      /{productVariantId}:
        uriParameters:
          productVariantId: string
        type:
           collection.readOnlyCollectionMember:
             collectionMemberResponseType: ProductVariantResponse
        get:
          responses: 
            200:
              body: 
                application/json:
                  example: |
                    {  
                       "productId":"eb8c8ca7-3c42-4489-a820-3aa138430b75",
                       "identifier":"88668866-2c6d-4fa6-9e17-4b2c42e0f051",
                       "identifiers":{  
                          "SKU":"UGG-BB-PUR-06"
                       },
                       "pictures":[  
                          "https://cdni.llbean.net/is/image/wim/251423_0_52??wid=428&hei=494",
                          "https://cdni.llbean.net/is/image/wim/251423_47_41?wid=428&hei=494"
                       ],
                       "configuration":[  
                          {  
                             "characteristic":{  
                                "code":"size",
                                "description":"Size",
                                "name":"Size of item"
                             },
                             "characteristicValue":{  
                                "code":"M",
                                "name":"Medium"
                             }
                          },
                          {  
                             "characteristic":{  
                                "code":"color",
                                "description":"Color",
                                "name":"Color"
                             },
                             "characteristicValue":{  
                                "code":"blue",
                                "name":"Blue"
                             }
                          }
                       ]
                    }
        /availability:
          type:
             collection.readOnlyCollectionMember:
               collectionMemberResponseType: ProductVariantAvailabilityResponse
          get:
            is: [ geoSearch]
            queryParameters: 
              quantity:
                required: false
                description: | 
                  Quantity requested. If quantity in particular store is less than requested, the store will not show up in the results.
                type: number
                default: 0
            responses:
              200: 
                body: 
                  application/json:
                    example: |
                        {
                          "productId": "122332665555",
                          "variantId": "88668866-2c6d-4fa6-9e17-4b2c42e0f051",
                          "warehousesAvailability": [
                            {
                              "warehouseId": "1",
                              "name": "Central Warehouse",
                              "availableCount": 100    
                            }
                          ], 
                          "partnersAvailability": [
                            {
                              "quantityInStock": 20,
                              "productPrice": 36.9,
                              "tax": 3.69,
                              "partnerInfo": {
                                "partnerId": "2d9df8be-a185-4dde-9577-d6edf6cdb398",
                                "name": "Best Amazing Store",
                                "description": "",
                                "email": "info@luckystore.example.com",
                                "phone": "+1-202-555-0119",
                                "url": "www.luckystore.example.com",
                                "shippingPrice": 5.5
                              }
                            }
                          ],   
                          "storesAvailability": [
                              {
                              "quantityInStock" : 55,
                              "storeInfo": {
                                "storeId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
                                "name": "Anypoint Store 1",
                                "description": "Department store chain providing brand-name c",
                                "notes": "",
                                "openingHours": "Mo,Tu,We,Th,Fr 08:00-18:00",
                                "address": {
                                  "streetLine1": "170 O'Farrell St",
                                  "streetLine2": "",
                                  "city": "San Francisco",
                                  "zipCode": "94102",
                                  "state": "California",
                                  "country": "USA"
                                },
                                "contact": {
                                  "email": "store1@anypointstore.example.com",
                                  "phone": "+1-202-555-0111"
                                },
                                "geo": {
                                  "latitude": 37.78703308105469,
                                  "longitude": -122.4060287475586
                                },
                                "distance": 0.12951756569805717,
                                "distanceUnit": "km"
                              }
                            }
                          ] 
                        }

/shoppingCarts:
  type:
    collection.collection:
      collectionResponseType: ShoppingCartCollectionResponse
      collectionMemberPrototypeType: session.ShoppingCart
      collectionMemberResponseType: ShoppingCartResponse
  get:
    is: &queryableCollection [ collection.pageable, collection.sortable ]
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "_links": {
                  "self": {
                    "href": "https://mocksvc.mulesoft.com/mocks/226604b1-d88b-4e3b-8a5c-4c299e70db6c/shoppingCarts/734a04dc-2f30-11e7-93ae-92361f002671"
                  }
                },
                "_meta": {
                  "messages": [],
                  "totalItems": 1,
                  "offset": 0,
                  "limit": 10            
                },
                "shoppingCarts": [
                  {
                    "identifier": "734a04dc-2f30-11e7-93ae-92361f002671",
                    "customerId": "11e7-93ae-92361f002671",
                    "items": [
                      {     
                        "location": {
                          "locationId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
                          "deliveryMethod": "PICKUP",
                          "locationType": "STORE"     
                        }, 
                        "item": {
                          "productId": "eb8c8ca7-3c42-4489-a820-3aa138430b75",
                          "identifier": "88668866-2c6d-4fa6-9e17-4b2c42e0f051",
                          "identifiers": {
                            "SKU": "UGG-BB-PUR-06"
                          },
                          "configuration": [
                            {
                              "characteristic": {
                                "code": "size",
                                "description": "Size",
                                "name": "Size of item"
                              },
                              "characteristicValue": {
                                "code": "M",
                                "name": "Medium"
                              }
                            },
                            {
                              "characteristic": {
                                "code": "color",
                                "description": "Color",
                                "name": "Color"
                              },
                              "characteristicValue": {
                                "code": "blue",
                                "name": "Blue"
                              }
                            }
                          ]
                        },
                        "quantity": {
                          "amount": 2,
                          "quantityType": "DISCRETE",
                          "unit": "EA"
                        }
                      }
                    ]
                  }
                ]
              }
  post:
      body:
        application/json:
          example: |
              { 
              "customerId": "provider_0123456789",
              "items": 
                  [
                    {
                      "location": {
                          "locationId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
                          "deliveryMethod": "PICKUP",
                          "locationType": "STORE"     
                       }, 
                      "item": {
                        "productId": "eb8c8ca7-3c42-4489-a820-3aa138430b75",
                        "identifier": "88668866-2c6d-4fa6-9e17-4b2c42e0f051"
                         
                      },
                      "quantity": {
                        "amount": 2,
                        "quantityType": "DISCRETE",
                        "unit": "EA"
                      }
                    },
                    {
                      "location": {
                          "locationId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
                          "deliveryMethod": "PICKUP",
                          "locationType": "STORE"     
                        }, 
                      "item": {
                        "productId": "eb8c8ca7-3c42-4489-a820-3aa138430b75",
                        "identifier": "88668866-2c6d-4fa6-9e17-4b2c42e0f051"
                      },
                      "quantity": {
                        "amount": 2,
                        "quantityType": "DISCRETE",
                        "unit": "EA"
                      }
                    }
                  ]
              }
      responses:
        201:
          body:
            application/json:
              example: |
                { 
                  "identifier": "88668866-2c6d-4fa6-9e17-4b2c42e0f051",
                  "customerId": "provider_0123456789",
                  "items": 
                    [
                        {
                          "location": {
                            "locationId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
                            "deliveryMethod": "PICKUP",
                            "locationType": "STORE"     
                          }, 
                          "item": {
                            "productId": "eb8c8ca7-3c42-4489-a820-3aa138430b75",
                            "identifier": "88668866-2c6d-4fa6-9e17-4b2c42e0f051",
                             "locationId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
                             "deliveryMethod": "PICKUP",
                              "locationType": "STORE" 
                          },
                          "quantity": {
                            "amount": 2,
                            "quantityType": "DISCRETE",
                            "unit": "EA"
                          }
                        },
                        {
                          "location": {
                            "locationId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
                            "deliveryMethod": "PICKUP",
                            "locationType": "STORE"     
                          }, 
                          "item": {
                            "productId": "cd67cd8a-8901-48c5-890b-0a21f4a0f8ad",
                            "identifier": "355d4130-1e3a-4795-aada-c960c89f6d9f"
                          },
                          "quantity": {
                            "amount": 1,
                            "quantityType": "DISCRETE",
                            "unit": "EA"
                          }
                        }
                   ]
                }
  /{shoppingCartId}:
    uriParameters:
      shoppingCartId: string
    type:
       collection.collectionMember:
         collectionMemberPrototypeType: session.ShoppingCart
         collectionMemberResponseType: ShoppingCartResponse
    get:
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "identifier": "734a04dc-2f30-11e7-93ae-92361f002671",
                  "customerId": "11e7-93ae-92361f002671",
                  "items": [
                    {
                      "location": {
                          "locationId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
                          "deliveryMethod": "PICKUP",
                          "locationType": "STORE"     
                        }, 
                      "item": {
                        "productId": "eb8c8ca7-3c42-4489-a820-3aa138430b75",
                        "identifier": "88668866-2c6d-4fa6-9e17-4b2c42e0f051",
                        "identifiers": {
                          "SKU": "UGG-BB-PUR-06"
                        },
                        "configuration": [
                          {
                            "characteristic": {
                              "code": "size",
                              "description": "Size",
                              "name": "Size of item"
                            },
                            "characteristicValue": {
                              "code": "M",
                              "name": "Medium"
                            }
                          },
                          {
                            "characteristic": {
                              "code": "color",
                              "description": "Color",
                              "name": "Color"
                            },
                            "characteristicValue": {
                              "code": "blue",
                              "name": "Blue"
                            }
                          }
                        ]
                      },
                      "quantity": {
                        "amount": 2,
                        "quantityType": "DISCRETE",
                        "unit": "EA"
                      }
                    }
                  ]
                }
    put:
      body:
        application/json:
          example: |
            { 
              "items": 
                [
                    {
                      "location": {
                          "locationId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
                          "deliveryMethod": "PICKUP",
                          "locationType": "STORE"     
                        },  
                      "item": {
                        "productId": "eb8c8ca7-3c42-4489-a820-3aa138430b75",
                        "identifier": "88668866-2c6d-4fa6-9e17-4b2c42e0f051"
                      },
                      "quantity": {
                        "amount": 2,
                        "quantityType": "DISCRETE",
                        "unit": "EA"
                      }
                    },
                    {
                      "location": {
                          "locationId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
                          "deliveryMethod": "PICKUP",
                          "locationType": "STORE"     
                        }, 
                      "item": {
                        "productId": "cd67cd8a-8901-48c5-890b-0a21f4a0f8ad",
                        "identifier": "355d4130-1e3a-4795-aada-c960c89f6d9f"
                      },
                      "quantity": {
                        "amount": 2,
                        "quantityType": "DISCRETE",
                        "unit": "EA"
                      }
                    }
               ]
            }
      responses:
        200:
          body:
            application/json:
              example: |
                { 
                  "items": 
                    [
                        {
                          "location": {
                            "locationId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
                            "deliveryMethod": "PICKUP",
                            "locationType": "STORE"     
                          }, 
                          "item": {
                            "productId": "eb8c8ca7-3c42-4489-a820-3aa138430b75",
                            "identifier": "88668866-2c6d-4fa6-9e17-4b2c42e0f051"
                          },
                          "quantity": {
                            "amount": 2,
                            "quantityType": "DISCRETE",
                            "unit": "EA"
                          }
                        },
                        {
                          "location": {
                            "locationId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
                            "deliveryMethod": "PICKUP",
                            "locationType": "STORE"     
                          }, 
                          "item": {
                            "productId": "cd67cd8a-8901-48c5-890b-0a21f4a0f8ad",
                            "identifier": "355d4130-1e3a-4795-aada-c960c89f6d9f"
                          },
                          "quantity": {
                            "amount": 2,
                            "quantityType": "DISCRETE",
                            "unit": "EA"
                          }
                        }
                   ]
                }
    delete:
      responses: 
        200:
          body: 
            application/json:
              example: |
                {
                  "_meta": {
                    "messages": []
                  }
                }
     