#%RAML 1.0
title: retail-partners-system-api
version: dev
baseUri: http://localhost:8081/api

traits: 
  productSearch: !include traits/productSearch.raml
      
types:
  PartnerInfo:
    type: object
    properties: 
      partnerId?: string
      name: string
      description?: string
      phone: string
      email: string
      url: string
      shippingPrice:
        type: number
        format: double

  ItemAvailabilityResponse:
    type: object
    properties: 
      searchCriteria: SearchCriteria
      results: PartnerAvailabilityData[]
      
  SearchCriteria:
    type: object
    properties: 
      name?: string?
      productId?: string?
      variantId?: string?
      quantity?: integer
      
  PartnerSearchResponse:
    type: object
    properties:
      searchCriteria: SearchCriteria
      results: PartnerInfo[]
      
  PartnerAvailabilityData:
    type: object
    properties: 
      partnerInfo: PartnerInfo
      quantityInStock: integer
      productPrice: number
      tax: number
      quantityReserved?: integer
      
  Reservation: 
    type: object
    properties:
      productId: string
      variantId: string
      customerId: string
      quantity: integer
      partnerId: string
      deliveryMethod: 
        type: string
        enum: [SHIPMENT, PICKUP]
         
      
/partners:
  get:
    queryParameters: 
      name: 
        type: string
        required: false
        description: |
          Partner name
      maxResults: 
        type: integer
        required: false
        default: 20
        description: |
          Maximum number of search results to return.
    responses: 
      200:
        body:
          application/json:
            type: PartnerSearchResponse
            example: !include examples/partner-search-response.raml
  post:
    description: creates new Partner record
    body: 
      application/json:
        type: PartnerInfo
        example: !include examples/create-partner-request.raml
    responses: 
      201:
        headers: 
          Location:
        body: 
          application/json:
            type: PartnerInfo
            example: !include examples/partner-response.raml
  
  /{partnerId}:
    uriParameters: 
      partnerId: 
        description: Partner identifier
    get:
      description: |
        Retrieve info about particular partner (address, name, etc.)
      responses: 
        200:
          body: 
            application/json:
              type: PartnerInfo
              example: !include examples/partner-response.raml
              
    put:
      description: | 
        Updates information about particular partner
      body: 
        application/json:
          type: PartnerInfo
          example: !include examples/partner-response.raml
      responses: 
        200:
          body: 
            application/json:
              type: PartnerInfo
              example: !include examples/partner-response.raml
      

/productSearch:
  get:
    description: |
      Searches for a product identified by productId and variantId. If quantity is provided as search parameter, only partners that have required number of items in stock are included in the response.
    is: [ productSearch ]
    responses: 
      200:
        body: 
          application/json:
            type: ItemAvailabilityResponse
            example: !include examples/product-search-response.raml

/reservation:           
  post:
    description: reservation of product
    body: 
      application/json:
        type: Reservation
        example: !include examples/product-reserve-request.raml
    responses: 
      201: 
        body: 
          application/json: 
            example: |
              {
                "message": "Product was reserved" 
              } 