#%RAML 1.0 Library

usage: |
  reusable cart order data types

uses:
  common: exchange_modules/47f07e0a-f578-47d4-9591-d9e7afffb0fc.retail/retail_common/1.0.10/retail_common.raml
  product: exchange_modules/47f07e0a-f578-47d4-9591-d9e7afffb0fc.retail/retail_product/1.0.10/retail_product.raml
types:

  ShoppingCartItem:
    description: |
      an individual component of an order
    properties:
      quantity:
        type: common.Quantity
        description: Quanitity of shopping cart item
      item:
        type: product.ProductVariant
        description: Specific variant of product
      location:
        type: common.Location
        description: |
          Where is your cart item located. It describes the type of location and possible delivery methods.
      tax?:
        type: number | nil
        description: Tax price for specific product.
      shipping?:
        type: number | nil
        description: Shipping price for specific product

  ShoppingCartItems: 
    type:  ShoppingCartItem[] | ItemSummary[]

  ShoppingCart:
    description: Information about the items in shopping cart
    type: object
    properties:
      identifier?: common.ResourceId
      customerId?:
        type: common.ResourceId
        description: Identifier of customer
      items?: 
        description: Collection of items in shopping cart
        type: ShoppingCartItems
      created?: 
        type: datetime
        description: | 
          timestamp of creating the shopping cart

  ItemSummary: 
    type: object
    properties: 
      productId: 
        type: string
        description: | 
          Identifier of product
      variantId: 
        type: string
        description: | 
          Identifier of variant
      location?: 
        type: common.Location
        description: 
          Location information
      quantity:  
        type: integer
        description: |
          Number of product (variant)
      tax?: 
        type: number | nil
        description: |
          total tax for product
      shipping?:
        type: number | nil
        description: |
          total shipping cost for product   
           