#%RAML 1.0 Library

usage: |
  resusable data types that describe merchandising product
  taxonomy, categories and hierarchies

uses:
  common: common-types.raml
  meta: metadata-types.raml
  hyper: hypermedia-types.raml

types:

  Category:
    properties:
      identifier: string
      abstract?: boolean
      parentId?: string
      name: string
      description: string  
