#%RAML 1.0
baseUri: http://localhost:8081/api
title: Retail Orders System API
version: dev

types: 

  OrderItem:
    type: object
    description: |
          Information about ordered product (variant)
    properties: 
      orderItemId: 
        type: string
        description: |
          Identifier of item which represents variantId
      productId: 
        type: string
        description: |
          Identifier of product
      productName:
        type: string
        description: |
          Name of product
      locationId: 
        type: string
        description: |
          Identifier of location (storeId or warehouseId or partnerId)
      deliveryMethod: 
        type: string 
        enum: [SHIPMENT, PICKUP]
        description: |
          Type of delivery
      quantity:  
        type: integer
        description: |
          Number of ordered product
  
  OrderItems: 
    type: object
    description: |
      Lists of ordered products (variant)
    properties: 
      pickupItems?: 
        type: OrderItem[]
        description: |
            Order Items in stores
      shipmentItems?: 
        type: OrderItem[]
        description: |
            Order Items in warehouses
      partnersItems?: 
        type: OrderItem[]
        description: |
            Order Items in partners shops
  
  StatusRequest:
    properties:
      status: Status
    
  Status:
    type: string
    enum: [Draft, Completed, Processing]
    
  Order:
    properties: 
      orderId? :
        type: string
        description: |
          Identifier of order
      customerId?: 
        type: string
        description: |
          Identifier of customer
      billingAddress?: 
        type: Address
        description: |
          full billing address of customer
      shippingAddress?: 
        type: Address
        description: |
          full address for shipping
      orderItems?:
        type: OrderItems
        description: |
          Lists of ordered products
      status?:
        type: Status
        description: |
          Status of order
      subtotal?: 
        type: string
        description: |
          price for order (without tax and shipping)
      shippingCost?: 
        type: string
        description: |
          total price of shipping
      totalTax?: 
        type: string
        description: |
          total price of shipping
      total?: 
        type: string
        description: |
          total price for order (with tax and shipping)
  

  Address:
    type: object
    properties:
      address?:
        type: string?
        description: |
          the unit number and street name
      city?:
        type: string?
        description: |
          the municipality of the address
      state?:
        type: string?
        description: |
          the state or other national region of the address
      postalCode?:
        type: string?
        description: |
          the delivery code assigned to this address by a national
          or governmental postal agency
      country?:
        type: string?
        description: |
          the two character ISO 3166 country code
          [http://www.iso.org/iso/home/standards/country_codes.htm]

      
/orders:
  /customer/{customerId}:
    displayName: Orders
    get:
      description: Lists the user orders
      queryParameters:
        trackingNumber:
          displayName: Order Tracking Number
          required: false
          type: string
      responses:
        200:
          body:
            application/json:
              type: Order[]
              example: !include examples/order_collection_get_response.raml
        404:
          body:
            application/json:
              example: |
                {
                  "message": "Resource not found"
                }
    post:
      description: Create a new Order.
      body:
        application/json:
          type: Order
          example: !include examples/order_post_request.raml
      responses:
        201:
          body:
            application/json:
              type: Order
              example: !include examples/order_post_response.raml
        400:
          body:
            application/json:
              example: |
                {
                  "message": "Bad Request"
                }
  /{orderId}:
    get:
      responses:
        200:
          body:
            application/json:
              type: Order
              example: !include examples/order_get_response.raml

        404:
          body:
            application/json:
              example: |
                {
                  "message": "Resource not found"
                }
    put:
      body:
        application/json:
          type: Order
          example:  !include examples/order_put_request.raml
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "message": "Order was updated"
                }
        400:
          body:
            application/json:
              example: |
                {
                  "message": "Bad Request"
                }
        404:
          body:
            application/json:
              example: |
                {
                  "message": "Order not found"
                }                    
    delete:
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "message": "Order was deleted"
                }
        400:
          body:
            application/json:
              example: |
                {
                  "message": "Bad Request"
                }
        404:
          body:
            application/json:
              example: |
                {
                  "message": "Order not found"
                }
    /status:
      displayName: Status
      put:
        body:
          application/json:
            type: StatusRequest
            example: !include examples/order_status_put_request.raml
        responses:
          200:
            body:
              application/json:
                example: |
                  {
                    "message": "Order status was updated"
                  }
          400:
            body:
              application/json:
                example: |
                  {
                    "message": "Bad Request"
                  }
          404:
            body:
              application/json:
                example: |
                  {
                    "message": "Order not found"
                  }