#%RAML 1.0 NamedExample
value: |
  {
    "customerId": "123456789",
    "orderItems": [
      {
        "orderItemId": "1",
        "productName": "Supersonic Charger",
        "quantity": 4
      }
    ],
    "status": "Draft",
    "price": "1304"
  }