#%RAML 1.0 NamedExample
value: |
      {  
        "orderId":"51c0ba3a-7e64-11e7-bb31-be2e44b06b34",
        "subtotal":"100.21",
        "totalTax":"15.22",
        "shippingCost":"10.00", 
        "total":"125.43",
        "shippingAddress":{
            "address":"Main Street 40",
            "city":"San Francisco", 
            "postalCode":"94210",
            "state":"CA",
            "country":"US"   
        },
        "billingAddress":{
            "address":"Main Street 40",
            "city":"San Francisco", 
            "postalCode":"94210",
            "state":"CA",
            "country":"US"   
        },
        "status":"Draft",
        "trackingNumber":"",
        "customerId":"1964401a-a8b3-40c1-b86e-d8b9f75b5842",
        "orderItems":
        {  
            "pickupItems": [  
                {  
                    "orderItemId":"88668866-2c6d-4fa6-9e17-4b2c42e0f051",
                    "productId":"eb8c8ca7-3c42-4489-a820-3aa138430b75",
                    "productName":"Smart Slim Micro Stripe Shirt",
                    "locationId":"1c9a20dc-c585-42fd-ac1a-1216085b76d2",
                    "deliveryMethod":"PICKUP",
                    "quantity":1
                },
                {  
                    "orderItemId":"dfc25820-c37d-456c-8867-4a89a51b7f75",
                    "productId":"7c9be8ad-0791-4362-b195-a53dcca4e1d7",
                    "productName":"Men's Regular Fit V-Neck Knit Sweater",
                    "locationId":"1c9a20dc-c585-42fd-ac1a-1216085b76d2",
                    "deliveryMethod":"PICKUP",
                    "quantity":2
                } 
            ],
            "shipmentItems": [  
                {  
                    "orderItemId":"3c1eb223-811c-4e86-8ea3-4a06a002a79a",
                    "productId":"cd67cd8a-8901-48c5-890b-0a21f4a0f8ad",
                    "productName":"Men's Chino Jogger Pants",
                    "locationId":"7307024a-7e63-11e7-bb31-be2e44b06b34",
                    "deliveryMethod":"SHIPMENT",
                    "quantity":3
                }
            ],
            "partnersItems": [  
                {  
                    "orderItemId":"fc3d4900-c5ac-4649-8bc8-cbbef4fe8fde",
                    "productId":"e1c515f9-102d-4830-b353-18fe48065732",
                    "productName":"Uniforms Modern Fit Short Sleeve Polo Shirt",
                    "locationId":"730704d4-7e63-11e7-bb31-be2e44b06b34",
                    "deliveryMethod":"SHIPMENT",
                    "quantity":1
                }
            ]
        }
      }