#%RAML 1.0 NamedExample
value: |
  {
    "productId": "cd67cd8a-8901-48c5-890b-0a21f4a0f8ad",
    "variantId": "beb3c34f-55b0-49c8-b7e2-5585727713ef",
    "locationId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
    "locationType": "STORE",
    "quantityInStock": 20,
    "tax": 3.8,
    "shipping": 0
  }