#%RAML 1.0 NamedExample
value: |
        {
            "quantityInStock" : 55,
            "storeInfo": {
              "storeId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
              "name": "Anypoint Store 1",
              "description": "Department store chain providing brand-name c",
              "notes": "",
              "openingHours": "Mo,Tu,We,Th,Fr 08:00-18:00",
              "address": {
                "streetLine1": "170 O'Farrell St",
                "streetLine2": "",
                "city": "San Francisco",
                "zipCode": "94102",
                "state": "California",
                "country": "USA"
              },
              "contact": {
                "email": "store1@anypointstore.example.com",
                "phone": "+1-202-555-0111"
              },
              "geo": {
                "latitude": 37.78703308105469,
                "longitude": -122.4060287475586
              },
              "distance": 0.12951756569805717,
              "distanceUnit": "km"
        }