#%RAML 1.0 NamedExample
value: |
      {
          "productId": "eb8c8ca7-3c42-4489-a820-3aa138430b75",  
          "variantId": "88668866-2c6d-4fa6-9e17-4b2c42e0f051",
          "customerId": "12324566545", 
          "locationId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
          "locationType": "WAREHOUSE",
          "quantity": 2
      }
      
