#%RAML 1.0 Library

usage: |
  reusable data types that describe merchandising product
  taxonomy, categories and hierarchies

types:

  Category:
    description: |
      product category
    properties:
      identifier: 
        type: string
        description: Identifier of category
      abstract?: 
        type: boolean
        description: Boolean value if the category is abstract
      parentId?: 
        type: string
        description: Identifier of paren category
      name:
        type: string
        description: Category name
      description: string
