#%RAML 1.0 NamedExample
value: |
  {
      "name": "Shop For You",
      "description": "",
      "email": "info@shopforyou.example.com",
      "phone": "+1-202-555-0146",
      "url": "www.shopforyou.example.com",
      "shippingPrice": 7.5
  }