#%RAML 1.0 NamedExample
value: |
  {
    "partnerId": "84c95f82-c435-4de0-8964-82e16bd23689",
    "name": "Shop For You",
    "description": "",
    "email": "info@shopforyou.example.com",
    "phone": "+1-202-555-0146",
    "url": "www.shopforyou.example.com",
    "shippingPrice": 7.5
  }