#%RAML 1.0 NamedExample
value: |
  {
    "productId": "7c9be8ad-0791-4362-b195-a53dcca4e1d7",
    "variantId": "6a3c6342-af6c-402a-9f63-55e76a0de99a",
    "customerId": "123456789",
    "quantity": 2,
    "deliveryMethod": "SHIPMENT",
    "partnerId": "123"
  }