#%RAML 1.0 NamedExample
value: |
  {
    "name": "Anypoint Store 1",
    "description": "Department store chain providing brand-name clothing and accessories",
    "notes": "",
    "openingHours": "Mo,Tu,We,Th,Fr 08:00-18:00",
    "contact" : {
      "email" : "store1@anypointstore.example.com",
      "phone" : "+1-202-555-0111"
    },
    "address" : {
      "streetLine1" : "170 O'Farrell St",
      "streetLine2" : "",
      "city" : "San Francisco",
      "zipCode" : "94102",
      "state" : "CA",
      "country" : "USA"
    },
    "geo" : {
      "latitude" : 37.7870342,
      "longitude" : -122.4060321
    }
  }