#%RAML 1.0 NamedExample
value: |
  {
    "searchCriteria": {
      "latitude": 37.7875925,
      "longitude": -122.404736,
      "radius": 10,
      "useMetric": true
    },
    "results": [
      {
        "storeId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
        "name": "Anypoint Store 1",
        "description": "Department store chain providing brand-name c",
        "notes": "",
        "openingHours": "Mo,Tu,We,Th,Fr 08:00-18:00",
        "address": {
          "streetLine1": "170 O'Farrell St",
          "streetLine2": "",
          "city": "San Francisco",
          "zipCode": "94102",
          "state": "California",
          "country": "USA"
        },
        "contact": {
          "email": "store1@anypointstore.example.com",
          "phone": "+1-202-555-0111"
        },
        "geo": {
          "latitude": 37.78703308105469,
          "longitude": -122.4060287475586
        },
        "distance": 0.12951756569805717,
        "distanceUnit": "km"
      },
      {
        "storeId": "47dc46d1-9a2a-4ca1-8063-22aab7ddcd45",
        "name": "Anypoint Store 2",
        "description": "Department store chain providing brand-name c",
        "notes": "",
        "openingHours": "Mo,Tu,We,Th,Fr 08:00-18:00",
        "address": {
          "streetLine1": "1 Stonestown Mall",
          "streetLine2": "",
          "city": "San Francisco",
          "zipCode": "94132",
          "state": "California",
          "country": "USA"
        },
        "contact": {
          "email": "store2@anypointstore.example.com",
          "phone": "+1-202-555-0124"
        },
        "geo": {
          "latitude": 37.72914505004883,
          "longitude": -122.4768295288086
        },
        "distance": 9.077742316846548,
        "distanceUnit": "km"
      }
    ]
  }