#%RAML 1.0 NamedExample
value:  |
    [
      {
        "shoppingCartId": "85643910-7e79-11e7-81f6-02d63613b776",
        "customerId": "951",
        "items": [
          {
            "productId": "eb8c8ca7-3c42-4489-a820-3aa138430b75",
            "variantId": "88668866-2c6d-4fa6-9e17-4b2c42e0f051",
            "quantity": 2, 
             "location": {
                "locationId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
                "locationType": "WAREHOUSE",
                "deliveryMethod": "SHIPMENT"
            }
          },
          {
            "productId": "cd67cd8a-8901-48c5-890b-0a21f4a0f8ad",
            "variantId": "355d4130-1e3a-4795-aada-c960c89f6d9f",
            "quantity": 1,
             "location": {
                "locationId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
                "locationType": "WAREHOUSE",
                "deliveryMethod": "SHIPMENT"
            }
          }
        ],
        "created": "2017-08-11T09:43:25.218Z"
      }
    ]
