#%RAML 1.0 NamedExample
value: |
    {
        "shoppingCartId": "278f1310-67bc-11e7-88f0-d88b20524153",
        "customerId": "provider_0123456789",
        "items": [
          {
            "location": {
                "locationId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
                "locationType": "WAREHOUSE",
                "deliveryMethod": "SHIPMENT"
            },
            "item": {
              "productId": "eb8c8ca7-3c42-4489-a820-3aa138430b75",
              "identifier": "88668866-2c6d-4fa6-9e17-4b2c42e0f051",
              "identifiers": {
                "SKU": "UGG-BB-PUR-06"
              },
              "configuration": [
                {
                  "characteristic": {
                    "code": "size",
                    "description": "Size",
                    "name": "Size of item"
                  },
                  "characteristicValue": {
                    "code": "M",
                    "name": "Medium"
                  }
                },
                {
                  "characteristic": {
                    "code": "color",
                    "description": "Color",
                    "name": "Color"
                  },
                  "characteristicValue": {
                    "code": "blue",
                    "name": "Blue"
                  }
                }
              ],
              "quantity": {
                "amount": 5,
                "quantityType": "DISCRETE",
                "unit": "EA"
              }
            }
          },
          {
            "item": {
              "productId": "cd67cd8a-8901-48c5-890b-0a21f4a0f8ad",
              "identifier": "355d4130-1e3a-4795-aada-c960c89f6d9f",
              "identifiers": {
                "SKU": "UGG-BB-PUR-06"
              },
              "configuration": [
                {
                  "characteristic": {
                    "code": "size",
                    "description": "Size",
                    "name": "Size of item"
                  },
                  "characteristicValue": {
                    "code": "L",
                    "name": "Large"
                  }
                },
                {
                  "characteristic": {
                    "code": "color",
                    "description": "Color",
                    "name": "Color"
                  },
                  "characteristicValue": {
                    "code": "tan",
                    "name": "Tan"
                  }
                }
              ],
              "quantity": {
                "amount": 3,
                "quantityType": "DISCRETE",
                "unit": "EA"
              },
               "location": {
                "locationId": "1c9a20dc-c585-42fd-ac1a-1216085b76d2",
                "locationType": "WAREHOUSE",
                "deliveryMethod": "SHIPMENT"
              }
            }
          }
        ]
      }